### ISSUE TITLE
Issue with .NET 4.5.2?

### ISSUE THREAD

**Issue by Leo40Git** [cooptex977/isaac-injector#7]
When I try to launch Rebirth, both the modloader and Rebirth stop working. This is the crashlog:

==========EXCEPTION==========
Message: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
Inner exception: 
Source: mscorlib
Target site: System.Reflection.RuntimeAssembly nLoadFile(System.String, System.Security.Policy.Evidence)
Stack trace:    at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at OML.Loader.GetPlugins()
   at OML.Handler.Handle()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

I'm pretty sure it's because I'm using .NET 4.5.2.

**Comment by kwasny** [comment]
did u unblock dll's ?

**Comment by Leo40Git** [comment]
Yeah, I did.

**Comment by kwasny** [comment]
this mod is dead i think

**Comment by omni-** [comment]
This error _only_ occurs when all the DLLs are not unblocked. Make sure to go through _all_ the folders in the project and look for ones you may have missed.

**Comment by Leo40Git** [comment]
OK. I'll reply again when I go through ALL the DLLs.
